name: Auto Assign Reviewer

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  assign-reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set Reviewer
        env:
          REVIEWER: "username" # replace with the username of the reviewer you want to assign
        run: |
          token="${{ secrets.GITHUB_TOKEN }}"
          pr_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          response=$(curl -X POST -H "Authorization: token $token" -H "Accept: application/vnd.github.v3+json" -d "{\"reviewers\":[\"$REVIEWER\"]}" "https://api.github.com/repos/$GITHUB_REPOSITORY/pulls/$pr_number/requested_reviewers" -w "\n%{http_code}")
          echo "$response"
          if [[ "$response" != *"2"* ]]; then
            echo "Failed to assign reviewer"
            exit 1
          fi
